name = "MadNLP"
uuid = "2621e9c9-9eb4-46b1-8089-e8c72242dfb6"
authors = ["Sungho Shin"]
repo = "https://github.com/sshin23/MadNLP.jl.git"
version = "0.3.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SolverCore = "ff4d7338-4cf1-434d-91df-b86cb86fb843"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SuiteSparse = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"

[compat]
MathOptInterface = "~0.9"
NLPModels = "~0.17.2"
SolverCore = "~0.1,~0.2"
julia = "1.3"
AmplNLReader = "~0.11"
MINLPTests = "~0.5"
MadNLPTests = "~0.3"

[extras]
AmplNLReader = "77dd3d4c-cb1d-5e09-9340-85030ff7ba66"
MadNLPTests = "b52a2a03-04ab-4a5f-9698-6a2deff93217"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
MINLPTests = "ee0a3090-8ee9-5cdb-b8cb-8eeba3165522"

[targets]
test = ["Test","MadNLPTests","AmplNLReader","MINLPTests", "Random"]
