name = "MadNLPBenchmark"
uuid = "1d160368-de00-43d7-a5d3-abd138c7a408"
version = "0.1.0"

[deps]
COPSBenchmark = "3c263af4-7bba-497b-afe4-00c59a0a48a5"
CUTEst = "1b53aba6-35b6-5f92-a507-53c67d53f819"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
ExaModelsPower = "2fff4b78-0b6c-428d-bac8-85ccea8c4bdf"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[sources]
COPSBenchmark = {rev = "8ad4d37", url = "https://github.com/MadNLP/COPSBenchmark.jl"}

[compat]
CUTEst = "1.3.6"
Distributed = "1.11.0"
ExaModelsPower = "0.2.0"
JLD2 = "0.6.3"
Logging = "1.11.0"
