[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ExaModels = "1037b233-b668-4ce9-9b63-f9f681f55dd2"
HybridKKT = "59d292e8-f99c-4495-a4cc-613f4397570f"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MadNLP = "2621e9c9-9eb4-46b1-8089-e8c72242dfb6"
MadNLPGPU = "d72a61cc-809d-412f-99be-fd81f4b8a598"
MadNLPTests = "b52a2a03-04ab-4a5f-9698-6a2deff93217"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
Quadmath = "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[sources]
HybridKKT = { url = "https://github.com/MadNLP/HybridKKT.jl", rev = "master" }
